apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-user
  namespace: civil3-backend
  labels:
    app: api-user
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: api-user
  template:
    metadata:
      labels:
        app: api-user
    spec:
      containers:
        - name: api-user
          image: registry.civil3.xyz/go-zero-devops/api@sha256:8c2bedd63d5696f3c7ee8d4ff56445299c4b9748da30e95b8133d1fa9af9deb3
          ports:
          - containerPort: 8888
          readinessProbe:
            tcpSocket:
              port: 8888
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8888
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          volumeMounts:
            - name: timezone
              mountPath: /etc/localtime
            - name: api-user
              mountPath: /app/etc/user-api.yaml
              subPath: user-api.yaml
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: api-user
          configMap:
            name: api-user

---

apiVersion: v1
kind: Service
metadata:
  name: api-user-svc
  namespace: civil3-backend
spec:
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    app: api-user

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: api-user-hpa-c
  namespace: civil3-backend
  labels:
    app: api-user-hpa-c
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-user
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: api-user-hpa-m
  namespace: civil3-backend
  labels:
    app: api-user-hpa-m
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-user
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: api-user
  namespace: civil3-backend
  labels:
  annotations:
data:
  user-api.yaml: |
    Name: user-api
    Host: 0.0.0.0
    Port: 8888

    User:
      Etcd:
        Hosts:
          - etcd-demo.civil3-backend:2379
        Key: user.rpc
